/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function add(a: number, b: number): number
export declare function substract(a: number, b: number): number
export declare function multiply(a: number, b: number): number
export declare function divide(a: number, b: number): number
